/* A throwaway CA for the loopback test server. Forced in ahead of
   network/ca_certs.h, whose guard it defines, so https.c trusts this and
   nothing else while the test runs. Generated by tools/nettest/run. */
#ifndef PSPDX_CA_CERTS_H
#define PSPDX_CA_CERTS_H
static const char PSPDX_CA_PEM[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBhjCCASugAwIBAgIUXDv3blzMDkj8IoyXBaZcttCnTmowCgYIKoZIzj0EAwIw\n"
    "GDEWMBQGA1UEAwwNcHNwZHggdGVzdCBDQTAeFw0yNjA5MTAxOTEyMzBaFw0yNjEw\n"
    "MTAxOTEyMzBaMBgxFjAUBgNVBAMMDXBzcGR4IHRlc3QgQ0EwWTATBgcqhkjOPQIB\n"
    "BggqhkjOPQMBBwNCAAQ3d+5WW8T/cUqDbzZ9i7cIRjcGvw6THiZOomppjOqNFnoV\n"
    "0bAhGA+ISYHiX1KxhNxH7DK1vvCy4k8fg2dNJcJ7o1MwUTAdBgNVHQ4EFgQUF0HI\n"
    "4j76TpxuPzh53KpE57FP/GAwHwYDVR0jBBgwFoAUF0HI4j76TpxuPzh53KpE57FP\n"
    "/GAwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNJADBGAiEA17OhrgzyLr/K\n"
    "ObT5D/VPW3GX7v05ViCjzXbDhSLiCCUCIQCnOLSBvKYshZQqBCnHfTqIs0HTaztU\n"
    "o4sjY70nw9hnMA==\n"
    "-----END CERTIFICATE-----\n";
#endif
