#!/usr/bin/env python3
"""Turns assets/marks/*.png into gui/marks_data.h.

The glyphs are white and nothing but their alpha varies, so the table is one
byte a pixel. The header is committed, which is why this reads PNG itself
rather than leaning on Pillow: regenerating the set must need no more than a
stock Python, and the Docker build needs neither.

    python3 tools/marks/embed.py

Run it from app/. It writes gui/marks_data.h in place.
"""

import os
import struct
import sys
import zlib

# The order here is the order of enum mark in gui/marks.h. Nothing keeps the
# two in step but this comment, so if a mark is added it goes in both.
ORDER = [
    'cross', 'circle', 'triangle', 'square',
    'tick', 'update', 'basket', 'stick', 'play', 'download', 'info',
    'all', 'games', 'demos', 'apps', 'emulators', 'plugins',
    'start', 'select', 'l', 'r', 'home',
]


def read_png(path):
    """The alpha plane of an 8-bit RGBA PNG. Only what this tool writes has
    to be read, so the exotic colour types and interlace are not handled --
    they are refused loudly instead of decoded wrongly."""
    with open(path, 'rb') as fh:
        data = fh.read()
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        raise ValueError(path + ': not a PNG')
    pos = 8
    idat = b''
    w = h = None
    while pos < len(data):
        (length,) = struct.unpack('>I', data[pos:pos + 4])
        kind = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + length]
        pos += 12 + length
        if kind == b'IHDR':
            w, h, depth, colour, comp, filt, inter = struct.unpack('>IIBBBBB', body)
            if (depth, colour, inter) != (8, 6, 0):
                raise ValueError(path + ': want 8-bit RGBA, not interlaced')
        elif kind == b'IDAT':
            idat += body
        elif kind == b'IEND':
            break
    raw = zlib.decompress(idat)
    stride = w * 4
    out = bytearray()
    prev = bytearray(stride)
    at = 0
    for _ in range(h):
        ftype = raw[at]
        line = bytearray(raw[at + 1:at + 1 + stride])
        at += 1 + stride
        for i in range(stride):
            a = line[i - 4] if i >= 4 else 0
            b = prev[i]
            c = prev[i - 4] if i >= 4 else 0
            if ftype == 1:
                line[i] = (line[i] + a) & 0xFF
            elif ftype == 2:
                line[i] = (line[i] + b) & 0xFF
            elif ftype == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif ftype == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
            elif ftype != 0:
                raise ValueError(path + ': unknown filter %d' % ftype)
        out += line[3::4]
        prev = line
    return w, h, bytes(out)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    app = os.path.dirname(os.path.dirname(here))
    src = os.path.join(app, 'assets', 'marks')
    dst = os.path.join(app, 'gui', 'marks_data.h')

    glyphs = []
    for name in ORDER:
        w, h, alpha = read_png(os.path.join(src, name + '.png'))
        glyphs.append((name, w, h, alpha))

    lines = []
    # No wildcard in the line: a "/*" inside a comment is a warning, and this
    # build is kept warning-free.
    lines.append('/* Generated by tools/marks/embed.py from the PNGs in'
                 ' assets/marks -- do not edit. */')
    lines.append('')
    lines.append('#ifndef PSPDX_MARKS_DATA_H')
    lines.append('#define PSPDX_MARKS_DATA_H')
    lines.append('')
    lines.append('/* The biggest glyph in the set, which is how much room the'
                 ' run finder needs. */')
    lines.append('#define MARK_MAX_W %d' % max(g[1] for g in glyphs))
    lines.append('#define MARK_MAX_H %d' % max(g[2] for g in glyphs))
    lines.append('')
    lines.append('struct mark_glyph {')
    lines.append('    const char *name;')
    lines.append('    unsigned char w, h;')
    lines.append('    const unsigned char *alpha;')
    lines.append('};')
    lines.append('')
    for name, w, h, alpha in glyphs:
        lines.append('static const unsigned char mark_px_%s[%d] = {' % (name, w * h))
        for y in range(h):
            row = alpha[y * w:(y + 1) * w]
            lines.append('    ' + ''.join('%4d,' % v for v in row))
        lines.append('};')
        lines.append('')
    lines.append('static const struct mark_glyph mark_glyphs[] = {')
    for name, w, h, _ in glyphs:
        lines.append('    { "%s", %d, %d, mark_px_%s },' % (name, w, h, name))
    lines.append('};')
    lines.append('')
    lines.append('#endif')
    lines.append('')

    with open(dst, 'w') as fh:
        fh.write('\n'.join(lines))
    sys.stderr.write('%s: %d glyphs\n' % (dst, len(glyphs)))


if __name__ == '__main__':
    main()
